import "./globals.css";
import { Montserrat } from "next/font/google"
import ClientLayout from "./client-layout"

const montserrat = Montserrat ({
  subsets: ["latin"],
  weight : ["200", "300", "400", "500", "600", "700", "800"]
})

export const metadata = {
  title: "Paramadeenah",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} $ antialiased`}
      >
        <ClientLayout>

        {children}
        </ClientLayout>
      </body>
    </html>
  );
}
